---
ansible_host: localhost
ansible_connection: local

project_params:
  NAMESPACE: "{{ namespace_name }}"
  IMAGE_NAMESPACE: "{{ image_namespace_name }}"
  DOCKER_REPO_URL: "{{ docker_repo_url }}"
  SERVICE: "{{ service }}"
  APP_NAME: "itorders"

deployment_config_params:
  IMAGE_VERSION: "{{ image_version if image_version is defined else 'latest' }}"

route_params:
  APPS_SUBDOMAIN: "{{ apps_subdomain if apps_subdomain is defined else omit }}"

openshift_cluster_content:
  - galaxy_requirements:
      - "{{ playbook_dir }}/roles/requirements.yml"
  - object: Create Application Resources
    pre_steps:
    - role: openshift_cluster_login
      vars:
        ocp_token: "{{ ocp_token }}"
        ocp_url: "{{ ocp_url }}"
    content:
      - name: Build Config
        template: "{{ playbook_dir }}/buildConfig.yaml"
        params_from_vars: "{{ project_params }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - create-build-config
      - name: Deployment Config
        template: "{{ playbook_dir }}/deploymentConfig.yaml"
        params_from_vars: "{{ project_params | combine(deployment_config_params) }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - deploy
      - name: Service
        template: "{{ playbook_dir }}/service.yaml"
        params_from_vars: "{{ project_params }}"
        namespace: "{{ project_params.NAMESPACE }}"
        tags:
          - deploy
      - name: Route
        template: "{{ playbook_dir }}/route.yaml"
        namespace: "{{ project_params.NAMESPACE }}"
        params_from_vars: "{{ project_params | combine(route_params) }}"
        tags:
          - deploy
