---
apiVersion: v1
kind: Template
metadata:
  name: deployment-config-template
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      replicas: 1
      selector:
        name: ${APP_NAME}
      strategy:
        type: Rolling
        rollingParams:
      template:
        metadata:
          labels:
            name: ${APP_NAME}
        spec:
          containers:
            - name: kieserver
              imagePullPolicy: Always
              image: ${DOCKER_REPO_URL}/${IMAGE_NAMESPACE}/${SERVICE}:${IMAGE_VERSION}
              volumeMounts:
                # - name: spring-config
                #   mountPath: /deployments/application.properties
                #   readOnly: true
                #   subPath: application.properties
                - name: jta-pvc
                  mountPath: /opt/app/target/transaction-logs
                  readOnly: false
          volumes:
            - name: jta-pvc
              persistentVolumeClaim:
                claimName: ${APP_NAME}-pvol
                readOnly: false
          imagePullSecrets:
            - name: artifactory-puller
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${APP_NAME}-pvol
      labels:
        app: ${APP_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${APP_NAME}-jta
      labels:
        app: ${APP_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
parameters:
  - name: NAMESPACE
    displayName: Openshift namespace (project)
    description: Openshift namespace (project) this application resides in
    required: true
  - name: IMAGE_NAMESPACE
    displayName: Docker image namespace
    description: The docker namespace that the image belongs to
    required: true
  - name: IMAGE_VERSION
    displayName: Image Version
    description: Docker image version
    required: true
  - name: DOCKER_REPO_URL
    displayName: Docker Repo URL
    description: Docker repository URL
    required: true
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name