---
apiVersion: v1
kind: Template
metadata:
  name: service-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      external: ${SERVICE}
    name: ${SERVICE}
  spec:
    ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
      name: http
    selector:
      name: ${APP_NAME}
    sessionAffinity: None
    type: ClusterIP
parameters:
  - name: SERVICE
    displayName: Service Name
    description: Service Name
    required: true
  - name: APP_NAME
    required: true
    description: The app name